baseURL: 'https://shankar-dh.github.io/Personal-blog/'
languageCode: 'en-us'
title: 'Dhanush'
theme: 'PaperMod'

params:
  ShowBreadCrumbs: true
  showReadingTime: true

menu:
  main:
    # - identifier: 'about'
    #   name: 'About'
    #   url: '/about/'
    #   weight: 10
    - identifier: 'post'
      name: 'Posts'
      url: '/Posts/'
      weight: 20
    - identifier: 'search'
      name: 'Search'
      url: '/search/'
      weight: 30


outputs:
  home:
    - HTML
    - RSS
    - JSON
